apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cziubqxou-java-quarkus-gitops
  description: This is GitOps manifest for cziubqxou-java-quarkus   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=cziubqxou-java-quarkus
    backstage.io/kubernetes-id: cziubqxou-java-quarkus 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: cziubqxou-java-quarkus-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:cziubqxou-java-quarkus
